version: '3.9'

services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: nova_control_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin 
    ports:
      - "5432:5432"

  web:
    build: .
    command: >
      bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
      - ./media:/app/media  
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DEBUG=1

  dash:
    image: nova_control_app:v1.0
    volumes:
      - ./media:/app/media
    ports:
      - "8050:8050"
    depends_on:
      - web

volumes:
  postgres_data:
