# Generated by Django 5.1 on 2024-08-29 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datainspect', '0002_operationalvariable_control_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operationalvariable',
            name='control_status',
        ),
        migrations.RemoveField(
            model_name='operationalvariable',
            name='error_rate',
        ),
        migrations.RemoveField(
            model_name='operationalvariable',
            name='response_time',
        ),
        migrations.RemoveField(
            model_name='operationalvariable',
            name='reward',
        ),
    ]
