# Generated by Django 5.1 on 2024-08-30 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datainspect', '0003_remove_operationalvariable_control_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operationalvariable',
            name='timestamp',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='performancemetric',
            name='timestamp',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='performancemetric',
            name='value',
            field=models.FloatField(default=0.0),
        ),
    ]
