# Generated by Django 5.1 on 2024-09-13 13:21

import datainspect.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datainspect', '0004_alter_operationalvariable_timestamp_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockDiagram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagram_name', models.CharField(max_length=100)),
                ('json_file', models.FileField(upload_to='block_diagrams/', validators=[datainspect.models.validate_json_extension])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CSVDataSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataset_name', models.CharField(max_length=100)),
                ('csv_file', models.FileField(upload_to='datasets/', validators=[datainspect.models.validate_csv_extension])),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DynamicSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_name', models.CharField(max_length=100)),
                ('json_file', models.FileField(upload_to='dynamic_systems/', validators=[datainspect.models.validate_json_extension])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RLTrainedModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=100)),
                ('version', models.CharField(max_length=50)),
                ('zip_file', models.FileField(upload_to='rl_models/', validators=[datainspect.models.validate_zip_extension])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='TrainedModel',
        ),
    ]
